### ISSUE TITLE
Provide ISO core standard predicates

### ISSUE THREAD

**Issue by ghost** [JalogTeam/Jalog#1]
How about providing ISO core standard predicates here:

https://jalogteam.github.io/Jalog_quick_reference.html 

For example integer/1 instead of is_integer/1 and catch/3 instead of trap/3, etc..

**Comment by ariokkon** [comment]
Our intent is to make Jalog sufficiently intuitive to Java programmers.

Our experience with different Prolog dialects has shown that standard conformance is not very important. Actually we implemented semi-automatic two-way conversion between Visual Prolog and a more conventional Prolog in one project (to allow developing and using the programs in two different environments).

We also found that Turbo Prolog is closer to C programmers' way of thinking than standard Prolog.

Therefore we chose Turbo Prolog for our model, especially in lexical syntax, although we are not going to imitate every detail.

Naming of library predicates is still under consideration.

**Comment by ghost** [comment]
You can get the ISO core standard for not that much 
bucks. In 2018 I was abled to obtain it for $30. Probably
cheaper than a Visual Prolog license. See also: 

https://groups.google.com/forum/#!msg/comp.lang.prolog/U0Qcxi5LUmA/xLCPIe6qAAAJ

I don't think ISO Prolog is comparable to Visual Prolog
formerly PDC Prolog, formerly Turbo Prolog. Visual 
Prolog has types, I even don't know whether it has an
 
is_integer/1 (or integer/1) predicate at all?

**Comment by ariokkon** [comment]
You're right. There are no type checking predicates in Turbo/PDC Prologs due to strong typing. Type checking is done in compile time.
