### ISSUE TITLE
Support for directive :- ['<filename>'] in Jalog?

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [JalogTeam/Jalog#2]
What is the recommended way to load a further
Prolog text file inside a Prolog text file. I tried this:
```
>java -jar jalog.jar -v
Jalog 1.3.1 by Ari Okkonen & Mikko Levanto 2021-11-23

>java -jar jalog.jar suite.p
*** Error in file suite.p Line: 33 Pos: 5
    :- ['nrev.p'].
```
Strange at is `['<filename>']` is outside the ISO core
Prolog standard, but it works in many Prolog systems.

**Comment by ariokkon** [comment]
\[_filename_\] is not supported. Use consult. E.g.
`:- consult("nrev.p").`
See: [Jalog Quick Reference](https://jalogteam.github.io/r1.3/Jalog_quick_reference.html) and [Jalog Language Reference](https://jalogteam.github.io/r1.3/Jalog_language_reference.html) for supported features and syntax.
