### ISSUE TITLE
Feature request include/1 directive

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [JalogTeam/Jalog#3]
Try the following:
```
java -jar jalog.jar suite.p
```
Then got this error:
```
*** Error in file file:C:\Users\rburs\Desktop\rr\suite.p Line: 33 Pos: 4
    :- include('nrev.p').
       ^
```
Would it be possible that Jalog supports the `include/1` directive?

**Comment by Jean-Luc-Picard-2021** [comment]
Unfortunately I have some GNU Prolog code, and using `consult/1`
instead `include/1` will make it incompatible, since GNU Prolog doesn't
understand consult/1 as a directive. I get:
```
/* GNU Prolog 1.5.0 */
:- consult('foo.p').
user:1: warning: unknown directive consult/1 - maybe use initialization/1 - directive ignored
```

See also here, consult/1 was suggested in the past, but somehow
the suggestion doesn't work so easy as it turns out now.

**Support for directive :- ['<filename>'] in Jalog?**
https://github.com/JalogTeam/Jalog/issues/2

**Comment by ariokkon** [comment]
Currently there is a problem. We have _Turbo Prolog_ set of language keywords. `include` belongs to that set. Some design decisions are needed to allow `include/1` directive.

**Comment by ariokkon** [comment]
Some design decision have been made. Predicate `include/1` will be included in the version r1.5 to be released soon. However, you have to **enclose the file name in double quotes**: `:- include("nrev.p").` . Single quotes mean a character constant, double quotes mean a string constant.

**Comment by Jean-Luc-Picard-2021** [comment]
There are no strings in the ISO core standard.
Why would one require that?

**Comment by ariokkon** [comment]
I have written industrial, heavy duty programs using Prolog. In those systems processing speed and careful memory use save money and time. Strings, if used properly, offer more efficient implementation for text processing.
_Jalog does not duplicate content of strings in string processing operations._ (Duplication of string contents leading to memory-full crashes was a problem with Turbo/PDC Prolog I used in 2000s.)

**Comment by Jean-Luc-Picard-2021** [comment]
Java had string sharing on substring() in its initial version to avoid 
what you possibly call duplication? Then they have abandoned it. Why?
